"""create orders table

Revision ID: ddb9d4259336
Revises: 
Create Date: 2026-09-14 18:17:52.095662

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'ddb9d4259336'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
