FROM python:3.12-slim

WORKDIR /app

COPY worker/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY shared/ ./shared/
COPY worker/app/ .

ENV PYTHONUNBUFFERED=1

CMD ["python", "main.py"]